# Generated by Django 4.2.7 on 2026-07-15 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website_url', models.URLField(max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='source_logos/')),
                ('bias_rating', models.CharField(choices=[('center', 'Centrist'), ('left', 'Leaning Left'), ('right', 'Leaning Right'), ('left_extreme', 'Far Left'), ('right_extreme', 'Far Right'), ('sensationalist', 'Sensationalist'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('credibility_score', models.IntegerField(default=50, help_text='0-100')),
                ('country', models.CharField(default='Nepal', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='tweets.newssource'),
        ),
        migrations.CreateModel(
            name='BiasVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('center', 'Centrist'), ('left', 'Leaning Left'), ('right', 'Leaning Right'), ('left_extreme', 'Far Left'), ('right_extreme', 'Far Right'), ('sensationalist', 'Sensationalist'), ('unknown', 'Unknown')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bias_votes', to='tweets.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('news', 'user')},
            },
        ),
    ]
